### ISSUE TITLE
`aws insight` is now `aws comprehend`

### ISSUE THREAD

**Issue by scottmalkie** [awsdocs/amazon-comprehend-developer-guide#10]
Batch processing examples for aws cli still use `aws insight` which doesn't seem to work anymore.

**Comment by cbigham** [comment]
I've updated the docs on GitHub. I'm working on updating the docs on the docs.aws.amazon.com Web site, they should be updated in a couple of hours. 

Thanks for your help,
Chuck Bigham
AWS Developer Docs
