### ISSUE TITLE
Quickly is not a verb...

### ISSUE THREAD

**Issue by gkirkpatrick** [awsdocs/amazon-comprehend-developer-guide#12]
I couldn't find where this file is since it's an announcement. 

But you guys will probably know where it is:

https://aws.amazon.com/about-aws/whats-new/2018/07/amazon-comprehend-now-supports-syntax-analysis/

```“The customers moved quickly when doors opened” allows a developer to understand the nouns (customers, doors) and the verb (quickly). ```

Quickly is not a verb. I'll leave the irony of this issue to you guys. :)

**Comment by cbigham** [comment]
Thanks Greg.

I've forwarded your comment along to the people that are responsible for the page. I'm sure that we'll get it fixed soon.

Chuck Bigham
AWS Developer Documentation
