### ISSUE TITLE
Semantic Issue with percentage

### ISSUE THREAD

**Issue by CallMeBW** [awsdocs/amazon-comprehend-developer-guide#14]
Regarding the usage of 10-20% of the documents for testing purposes, shouldn't it say 
"we ensure that there are **no labels** in the test set **which we have seen before**"
instead of 
"we ensure that there are no labels in the test set which we have **never** seen before"

**Comment by ebattalio** [comment]
Topic was updated, see https://docs.aws.amazon.com/comprehend/latest/dg/how-document-classification-training.html#testing-the-model.
