### ISSUE TITLE
Precision request on escape character for "Training a Custom Classifier"

### ISSUE THREAD

**Issue by hervenivon** [awsdocs/amazon-comprehend-developer-guide#18]
In the Documentation "Training a Custom Classifier" (in `how-document-classification-training.md`) there is a mention to escaped commas in the training dataset `CSV` file but it is for labels only and no example is given.

I tried several typical escaping characters one can usually use with `CSV` files such as `\` or `"` but none of them has worked.

I ended with replacing comma with the html version of it: `"&#44;"`.

What is the official escaping method for comma in the document or label? Could you please provide an example.

**Comment by ebattalio** [comment]
Commas inside of quotes should be seen as part of the quoted string. 

Double check your file. Use pandas read_csv (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) to read a file. If it parses it as valid CSV, then amazon Comprehend should be able to as well.

**Comment by hervenivon** [comment]
Hi, thank you.

It would be really interesting to add that precision and maybe an example in the documentation.
