### ISSUE TITLE
comprehend-ssie-annotation-tool-cli.py file errors

### ISSUE THREAD

**Issue by fvrensburg** [awsdocs/amazon-comprehend-developer-guide#25]
The Python script file has errors from line 18-21.
 File "bin/comprehend-ssie-annotation-tool-cli.py", line 18, in <module>
    from utils.s3_helper import S3Client
ModuleNotFoundError: No module named 'utils.s3_helper'

Could there be missing steps in the Uploading a PDF to an S3 bucket section?
Or is current script out dated? 

Tested and script work, perhaps update instructions to first run - `pipenv shell` before executing script, missing instructions on AWS page

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
