### ISSUE TITLE
Can we walk customer through an example :Tutorial  for async document processing from console

### ISSUE THREAD

**Issue by initmahesh** [awsdocs/amazon-comprehend-developer-guide#27]
Hi 
Going through the documents , it seems like we have a lot of steps can we please add a tutorial where we take a use case and walk the customer through each step.
These steps specially were not very easy to implement: https://github.com/awsdocs/amazon-comprehend-developer-guide/blob/master/doc_source/analysis-jobs.md

Cheers
Mahesh Yadav

**Comment by devlinbd2** [comment]
I will add that to our list of possible enhancements.
